@startuml

title __MAIN's Class Diagram__\n

  package main {
    abstract class Direction {
        # angle : int
        + Direction()
        {abstract} + getAngle()
        + setAngle()
        + addAngle()
        {abstract} + move()
        {abstract} + turnLeft()
        {abstract} + turnRight()
    }
  }

  package main {
      class Application {
         {static} + main()
      }
  }
  

  package main {
    class DrawPanel {
        ~ cars : ArrayList<Car>
        {static} - detectedOS : OSType
        + DrawPanel()
        # paintComponent()
        + getImage()
        - getOperatingSystemType()
    }
  }
  

  package main {
    enum OSType {
      Windows
      MacOS
      Linux
    }
  }
  

  class AccessibleJPanel {
      # AccessibleJPanel()
      + getAccessibleRole()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleFocusHandler {
      # AccessibleFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  abstract class AccessibleJComponent {
      - propertyListenersCount : int
      # accessibleFocusHandler : FocusListener
      # AccessibleJComponent()
      + addPropertyChangeListener()
      + removePropertyChangeListener()
      # getBorderTitle()
      + getAccessibleName()
      + getAccessibleDescription()
      + getAccessibleRole()
      + getAccessibleStateSet()
      + getAccessibleChildrenCount()
      + getAccessibleChild()
      ~ getAccessibleExtendedComponent()
      + getToolTipText()
      + getTitledBorderText()
      + getAccessibleKeyBinding()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleFocusHandler {
      # AccessibleFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  class ActionStandin {
      - actionListener : ActionListener
      - command : String
      - action : Action
      ~ ActionStandin()
      + getValue()
      + isEnabled()
      + actionPerformed()
      + putValue()
      + setEnabled()
      + addPropertyChangeListener()
      + removePropertyChangeListener()
  }
  

  class IntVector {
      ~ array : int[]
      ~ count : int
      ~ capacity : int
      ~ IntVector()
      ~ size()
      ~ elementAt()
      ~ addElement()
      ~ setElementAt()
  }
  

  class KeyboardState {
      {static} - keyCodesKey : Object
      ~ KeyboardState()
      {static} ~ getKeyCodeArray()
      {static} ~ registerKeyPressed()
      {static} ~ registerKeyReleased()
      {static} ~ keyIsPressed()
      {static} ~ shouldProcess()
  }
  

  class ReadObjectCallback {
      - roots : Vector<JComponent>
      - inputStream : ObjectInputStream
      ~ ReadObjectCallback()
      + validateObject()
      - registerComponent()
  }
  

  class AccessibleAWTContainer {
      {static} - serialVersionUID : long
      - propertyListenersCount : int
      # accessibleContainerHandler : ContainerListener
      # AccessibleAWTContainer()
      + getAccessibleChildrenCount()
      + getAccessibleChild()
      + getAccessibleAt()
      + addPropertyChangeListener()
      + removePropertyChangeListener()
  }
  

  class AccessibleContainerHandler {
      # AccessibleContainerHandler()
      + componentAdded()
      + componentRemoved()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  class DropTargetEventTargetFilter {
      {static} ~ FILTER : EventTargetFilter
      - DropTargetEventTargetFilter()
      + accept()
  }
  

  interface EventTargetFilter {
      {abstract} + accept()
  }
  

  class MouseEventTargetFilter {
      {static} ~ FILTER : EventTargetFilter
      - MouseEventTargetFilter()
      + accept()
  }
  

  class WakingRunnable {
      ~ WakingRunnable()
      + run()
  }
  

  class AWTTreeLock {
      ~ AWTTreeLock()
  }
  

  abstract class AccessibleAWTComponent {
      {static} - serialVersionUID : long
      - propertyListenersCount : int
      # accessibleAWTComponentHandler : ComponentListener
      # accessibleAWTFocusHandler : FocusListener
      # AccessibleAWTComponent()
      + addPropertyChangeListener()
      + removePropertyChangeListener()
      + getAccessibleName()
      + getAccessibleDescription()
      + getAccessibleRole()
      + getAccessibleStateSet()
      + getAccessibleParent()
      + getAccessibleIndexInParent()
      + getAccessibleChildrenCount()
      + getAccessibleChild()
      + getLocale()
      + getAccessibleComponent()
      + getBackground()
      + setBackground()
      + getForeground()
      + setForeground()
      + getCursor()
      + setCursor()
      + getFont()
      + setFont()
      + getFontMetrics()
      + isEnabled()
      + setEnabled()
      + isVisible()
      + setVisible()
      + isShowing()
      + contains()
      + getLocationOnScreen()
      + getLocation()
      + setLocation()
      + getBounds()
      + setBounds()
      + getSize()
      + setSize()
      + getAccessibleAt()
      + isFocusTraversable()
      + requestFocus()
      + addFocusListener()
      + removeFocusListener()
  }
  

  class AccessibleAWTComponentHandler {
      # AccessibleAWTComponentHandler()
      + componentHidden()
      + componentShown()
      + componentMoved()
      + componentResized()
  }
  

  class AccessibleAWTFocusHandler {
      # AccessibleAWTFocusHandler()
      + focusGained()
      + focusLost()
  }
  

  enum BaselineResizeBehavior {
    CONSTANT_ASCENT
    CONSTANT_DESCENT
    CENTER_OFFSET
    OTHER
  }
  

  class BltBufferStrategy {
      # caps : BufferCapabilities
      # backBuffers : VolatileImage[]
      # validatedContents : boolean
      # width : int
      # height : int
      - insets : Insets
      # BltBufferStrategy()
      + dispose()
      # createBackBuffers()
      + getCapabilities()
      + getDrawGraphics()
      ~ getBackBuffer()
      + show()
      ~ showSubRegion()
      # revalidate()
      ~ revalidate()
      + contentsLost()
      + contentsRestored()
  }
  

  class BltSubRegionBufferStrategy {
      # BltSubRegionBufferStrategy()
      + show()
      + showIfNotLost()
  }
  

  class DummyRequestFocusController {
      - DummyRequestFocusController()
      + acceptRequestFocus()
  }
  

  class FlipBufferStrategy {
      # numBuffers : int
      # caps : BufferCapabilities
      # drawBuffer : Image
      # drawVBuffer : VolatileImage
      # validatedContents : boolean
      ~ width : int
      ~ height : int
      # FlipBufferStrategy()
      # createBuffers()
      - updateInternalBuffers()
      # getBackBuffer()
      # flip()
      ~ flipSubRegion()
      # destroyBuffers()
      + getCapabilities()
      + getDrawGraphics()
      # revalidate()
      ~ revalidate()
      + contentsLost()
      + contentsRestored()
      + show()
      ~ showSubRegion()
      + dispose()
  }
  

  class FlipSubRegionBufferStrategy {
      # FlipSubRegionBufferStrategy()
      + show()
      + showIfNotLost()
  }
  

  class ProxyCapabilities {
      - orig : BufferCapabilities
      - ProxyCapabilities()
  }
  

  enum VSyncType {
    VSYNC_DEFAULT
    VSYNC_ON
    VSYNC_OFF
    id
  }
  

  class FlipContents {
      {static} - I_UNDEFINED : int
      {static} - I_BACKGROUND : int
      {static} - I_PRIOR : int
      {static} - I_COPIED : int
      {static} - NAMES : String[]
      {static} + UNDEFINED : FlipContents
      {static} + BACKGROUND : FlipContents
      {static} + PRIOR : FlipContents
      {static} + COPIED : FlipContents
      - FlipContents()
  }
  

  class SingleBufferStrategy {
      - caps : BufferCapabilities
      + SingleBufferStrategy()
      + getCapabilities()
      + getDrawGraphics()
      + contentsLost()
      + contentsRestored()
      + show()
  }
  

  package main {
    interface IMoveable {
        {abstract} + move()
        {abstract} + turnLeft()
        {abstract} + turnRight()
    }
  }
  

  package main {
    class Perpendicular {
        + Perpendicular()
        + getAngle()
        + addAngle()
        + move()
        + turnLeft()
        + turnRight()
    }
  }
  

  DrawPanel -up-|> JPanel
  DrawPanel +-down- OSType
  DrawPanel +-down- AccessibleJPanel
  DrawPanel +-down- AccessibleJComponent
  DrawPanel +-down- ActionStandin
  DrawPanel +-down- IntVector
  DrawPanel +-down- KeyboardState
  DrawPanel +-down- ReadObjectCallback
  DrawPanel +-down- AccessibleAWTContainer
  DrawPanel +-down- DropTargetEventTargetFilter
  DrawPanel +-down- EventTargetFilter
  DrawPanel +-down- MouseEventTargetFilter
  DrawPanel +-down- WakingRunnable
  DrawPanel +-down- AWTTreeLock
  DrawPanel +-down- AccessibleAWTComponent
  DrawPanel +-down- BaselineResizeBehavior
  DrawPanel +-down- BltBufferStrategy
  DrawPanel +-down- BltSubRegionBufferStrategy
  DrawPanel +-down- DummyRequestFocusController
  DrawPanel +-down- FlipBufferStrategy
  DrawPanel +-down- FlipSubRegionBufferStrategy
  DrawPanel +-down- ProxyCapabilities
  DrawPanel +-down- SingleBufferStrategy
  AccessibleJPanel -up-|> AccessibleJComponent
  AccessibleJPanel +-down- AccessibleContainerHandler
  AccessibleJPanel +-down- AccessibleFocusHandler
  AccessibleJPanel +-down- AccessibleContainerHandler
  AccessibleJPanel +-down- AccessibleAWTComponentHandler
  AccessibleJPanel +-down- AccessibleAWTFocusHandler
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleFocusHandler -up-|> FocusListener
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  AccessibleJComponent -up-|> AccessibleExtendedComponent
  AccessibleJComponent -up-|> AccessibleAWTContainer
  AccessibleJComponent +-down- AccessibleContainerHandler
  AccessibleJComponent +-down- AccessibleFocusHandler
  AccessibleJComponent +-down- AccessibleContainerHandler
  AccessibleJComponent +-down- AccessibleAWTComponentHandler
  AccessibleJComponent +-down- AccessibleAWTFocusHandler
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleFocusHandler -up-|> FocusListener
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  ActionStandin -up-|> Action
  KeyboardState -up-|> Serializable
  ReadObjectCallback -up-|> ObjectInputValidation
  AccessibleAWTContainer -up-|> AccessibleAWTComponent
  AccessibleAWTContainer +-down- AccessibleContainerHandler
  AccessibleAWTContainer +-down- AccessibleAWTComponentHandler
  AccessibleAWTContainer +-down- AccessibleAWTFocusHandler
  AccessibleContainerHandler -up-|> ContainerListener
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  DropTargetEventTargetFilter -up-|> EventTargetFilter
  MouseEventTargetFilter -up-|> EventTargetFilter
  WakingRunnable -up-|> Runnable
  AccessibleAWTComponent -up-|> Serializable
  AccessibleAWTComponent -up-|> AccessibleComponent
  AccessibleAWTComponent -up-|> AccessibleContext
  AccessibleAWTComponent +-down- AccessibleAWTComponentHandler
  AccessibleAWTComponent +-down- AccessibleAWTFocusHandler
  AccessibleAWTComponentHandler -up-|> ComponentListener
  AccessibleAWTFocusHandler -up-|> FocusListener
  BltBufferStrategy -up-|> BufferStrategy
  BltSubRegionBufferStrategy -up-|> SubRegionShowable
  BltSubRegionBufferStrategy -up-|> BltBufferStrategy
  DummyRequestFocusController -up-|> RequestFocusController
  FlipBufferStrategy -up-|> BufferStrategy
  FlipSubRegionBufferStrategy -up-|> SubRegionShowable
  FlipSubRegionBufferStrategy -up-|> FlipBufferStrategy
  ProxyCapabilities -up-|> ExtendedBufferCapabilities
  ProxyCapabilities +-down- VSyncType
  ProxyCapabilities +-down- FlipContents
  FlipContents -up-|> AttributeValue
  SingleBufferStrategy -up-|> BufferStrategy
  Perpendicular -up-|> Direction


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
